version: '3.7'

services: 
  backserver:
    container_name: cg_backserver
    build: ./docker/apache
    volumes:
      - ./docker/config/vhosts:/etc/apache2/sites-enabled
      - ./backend:/home/wwwroot
    ports:
      - 80:80
    depends_on:
      - php   

  php:
    container_name: cg_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/home/wwwroot
    user: ${CURRENT_UID}
    depends_on:
      - db
  
  db:
    container_name: cg_mysql
    image: mysql:5.7
    volumes:
      - ./docker/data/db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    user: ${CURRENT_UID}
    ports:
      - 3306:3306
  
  node:
    container_name: cg_node
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
        - ./frontend:/home/wwwroot
    user: ${CURRENT_UID}
    ports:
        - 3001:3000
    tty: true
